version: "3"

vars:
  # Assumes MacOS
  DOCKER_MCP_CLI_PLUGIN_DST: $HOME/.docker/cli-plugins/docker-agent

tasks:
  tidy:
    desc: Tidy the project
    cmd: go mod tidy

  build:
    desc: Build the agent plugin
    cmd: go build -o ./bin/docker-agent ./cmd/agent
    env:
      CGO_ENABLED: 0
  
  install:
    desc: Install the agent plugin
    deps: [build]
    cmds:
      - rm {{.DOCKER_MCP_CLI_PLUGIN_DST}} || true
      - cp ./bin/docker-agent {{.DOCKER_MCP_CLI_PLUGIN_DST}}
  
  generate-from-mcp:
    desc: Generate agents from the mcp registry
    cmd: go run ./cmd/generate