name: docker_agent
model: '{{.Model}}'
description: 'An agent that wraps an mcp server. The MCP server description is: Use the Docker CLI.'
toolsets:
    - type: mcp
      command: docker
      args:
        - mcp
        - gateway
        - run
        - --servers=docker
        - --config={{.Root}}/gateway-config.yaml
instruction: |-
    You are an agent that specializes in using the docker mcp server. Its description is as follows:
    ```Use the Docker CLI.```
    Your purpose is to fulfill requests using the mcp server tools provided.
think: {{.Think}}
