name: kubernetes_agent
model: '{{.Model}}'
description: 'An agent that wraps an mcp server. The MCP server description is: Connect to a Kubernetes cluster and manage it.'
toolsets:
    - type: mcp
      command: docker
      args:
        - mcp
        - gateway
        - run
        - --servers=kubernetes
        - --config={{.Root}}/gateway-config.yaml
instruction: |-
    You are an agent that specializes in using the kubernetes mcp server. Its description is as follows:
    ```Connect to a Kubernetes cluster and manage it.```
    Your purpose is to fulfill requests using the mcp server tools provided.
